# languages.toml
# :lsp-restart

[[language]]
# https://rust-analyzer.github.io/manual.html#configuration
# [rust-analyzer] in rust-analyzer config documentation is translated to: 
# [language-server.rust-analyzer.config] 
name = "rust"
language-servers = [ "rust-analyzer" ]
# text-width = 60 # uncomment to check if language is enabled

[language-server.rust-analyzer]
# environment = { "ENV1" = "value1", "ENV2" = "value2" }

[language-server.rust-analyzer.config]
cachePriming.enable = false
check.command = "clippy"

