theme = "gruvbox"

[editor]
line-number = "relative"
true-color = true
rulers = [80]
bufferline = "multiple"
{{ if eq .chezmoi.os "windows" }}
shell = ["pwsh.exe","-NoLogo","-NoProfile","-NoProfileLoadTime","-Command","$PSStyle.OutputRendering='PlainText';"]
{{ end }}

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
