# To change, edit this file:
# .local\share\chezmoi\.chezmoitemplates\helix\config.toml
# and then 
# chezmoi apply $env:HOMEPATH\AppData\Roaming\helix\config.toml
# or
# chezmoi apply .config\helix\config.toml.tmpl
#
# local helix config files are in a local .helix directory, these include:
# .helix/config.toml (configuration) and .helix/ignore (file-picker)
# 
# :config-reload
theme = "gruvbox_dark_hard"

[editor]
# enables better cross platform work, now that Windows doesn't need CRLF
# `git config --global core.autocrlf input` for git config
default-line-ending = "lf"
insert-final-newline = false
# line-number = "relative"
# cursorcolumn = true # uncomment to check config works
undercurl = true # override automatic detection 
true-color = true # override automatic detection 
rulers = [80]
bufferline = "multiple"
{{ if eq .chezmoi.os "windows" -}} 
# template `if eq .chezmoi.os "windows" -` 
shell = ["pwsh.exe","-NoLogo","-NoProfile","-NoProfileLoadTime","-Command","$PSStyle.OutputRendering='PlainText';"]
#template `- end `
{{- end }}
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "file-type"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
# hidden = false

# [editor.whitespace]
# render = "all"

# [editor.indent-guides]
# render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
