theme = "gruvbox"

[editor]
line-number = "relative"
true-color = true
rulers = [80]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
